### ISSUE TITLE
USER STORY: Product Details Page

### ISSUE THREAD

**Issue by KlaraMartinsson** [KlaraMartinsson/bombastic-baths#18]
EPIC: #1 Viewing and Navigation

As a **viewer** I can **access detailed information on individual bath bombs** so that **I can make decisions about my purchase.**

## Acceptance Criteria
- The product details page displays high-quality images of the bath bomb.
- Detailed information such as ingredients, scent and price is provided.
- An "Add to Cart" button is available, allowing customers to easily add the product to their shopping cart.

## Tasks
- [x] Design the layout for the product detail page.
- [x] Integrate a cloud based system to display clear and high-resolution product images on each product details page.
- [x] Retrieve and display product information from the database.
