### ISSUE TITLE
USER STORY: Categories

### ISSUE THREAD

**Issue by KlaraMartinsson** [KlaraMartinsson/bombastic-baths#19]
EPIC: #4 Searching and Sorting

As a **visitor** I can **browse products by categories** so that **I can easily find the bath bombs that meet my preferences**.

## Acceptance Criteria
- The website has a navigation menu dedicated to product categories. The menu provides categories such as scent, colour, ingredients, gift kits, benefit and mood.
- The category navigation is consistent and available on all pages of the website.
-  Each category is clickable and leads to a dedicated page displaying products within that category.
-  The category page displays relevant products with images, descriptions, and prices.

## Tasks
- [x] Implement a category menu in the navbar.
- [x] Develop a a feature that categories the websites products.
- [x] Design the layout of the page that displays product categories.
- [x] Test the category functionality to guarantee accurate and consistent results.
