### ISSUE TITLE
USER STORY: Optimize Website for Search Engines

### ISSUE THREAD

**Issue by KlaraMartinsson** [KlaraMartinsson/bombastic-baths#36]
EPIC: #1 Viewing and Navigation

As a **store owner**, I want the **website to be optimized for search engines (SEO)** so that **the website ranks higher in search engine results and attracts more traffic**.

## Acceptance Criteria
- The website appears higher in search engine results when relevant keywords are used.
- The website's structure and content are optimized for search engine indexing.
- Images on the website have descriptive alt text to ensure they are properly indexed by search engines.
- The website's sitemap is submitted to search engines for indexing and crawling.
- Have a robot.txt file to tell search engines where they are not allowed to go on a website. Which enhancing SEO ranking by signaling quality.

## Tasks
- [ ] Perform keyword research to identify relevant keywords for the website's content.
- [ ] Implement HTML elements (headings, strong, emphasis, anchor tags) with appropriate keywords.
- [ ] Ensure that anchor text between anchor tags contains relevant keywords.
- [ ] Fill metadata tags with relevant keywords and description.
- [ ] Optimize image descriptions (alt attributes) and image file names with relevant keywords.
- [ ] Utilize the rel="noopener" attribute in anchor tags to prevent search engines from including irrelevant links in their assessment of the web page. Such as Facebook or Instagram.
- [ ] Create a sitemap for the website and submit it to search engines for indexing.
- [ ]  Create a robots.txt file and specify disallowed areas for search engine crawlers.
