### ISSUE TITLE
USER STORY: Social Media Marketing

### ISSUE THREAD

**Issue by KlaraMartinsson** [KlaraMartinsson/bombastic-baths#38]
EPIC: #37 SEO and Web Marketing

As a **site owner** I want **the website to enhance web marketing efforts** so that **it can increase online visibility and attract more visitors to my website.**

## Acceptance Criteria
- Use social media marketing, to connect with the target audience, share engaging content, and foster relationships with customers.

## Tasks
- [ ] Research other ecommerce businesses that sell similar products and see what marketing practices they employ.
- [ ] Create a Facebook page for the business.
- [ ] Create other social media plattforms if there is time.
