### ISSUE TITLE
USER STORY: Home Page

### ISSUE THREAD

**Issue by KlaraMartinsson** [KlaraMartinsson/bombastic-baths#44]
EPIC: #1 Viewing and Navigation

As a **visitor**, I can **access the home page** so that **I quickly understand what the website is about.**

## Acceptance Criteria
- It is easy to understand what the purpose of the website is.
- It shows the websites logo.
- The design and layout is visually appealing.

## Tasks
- [ ] Set up a homepage.
- [ ] Make it clear what the website is about, with text and high-quality images.
- [ ] Design a good looking logo and have it near the navigation bar.
- [ ] Optimize the home page for fast loading times and ensure it is responsive across different devices.
