### ISSUE TITLE
USER STORY: Navigation

### ISSUE THREAD

**Issue by KlaraMartinsson** [KlaraMartinsson/bombastic-baths#8]
EPIC: #1 Viewing and Navigation

As a **visitor** I can **easily navigate the webpage** so that **I can access what I'm looking for.**

## Acceptance Criteria
- User can easily find the navigation menu at the top of each page.
- User can navigate through the different pages.

## Tasks
- [ ]  Create a clear navigation menu.
- [ ]  Make sure that all of the links are operational.
- [ ]  Test the navigation bar's functionality and appearance on different devices and screen sizes
